### ISSUE TITLE
[Feature] Better error message for failed msa runs

### ISSUE THREAD

**Issue by jesuissumin** [seoklab/alphafold#2]
> I0803 18:49:00.794053 22923631028032 templates.py:856] Using precomputed obsolete pdbs /applic/AlphaFold/current/data/pdb_mmcif/obsolete.dat.
I0803 18:49:00.798075 22923631028032 run_alphafold.py:678] Have 5 models: [0, 1, 2, 3, 4]
I0803 18:49:00.798149 22923631028032 run_alphafold.py:683] Using random seed 518390027455843538 for the data pipeline
I0803 18:49:00.798281 22923631028032 run_alphafold.py:533] Predicting T01_rec_inactive
I0803 18:49:00.799394 22923631028032 jackhmmer.py:135] Launching subprocess "/opt/conda/envs/alphafold2/bin/jackhmmer -o /dev/null -A /tmp/tmp49fe_efk/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 ../input_seq/T01_rec.fa /applic/AlphaFold/current/data/uniref90/uniref90.fasta"
I0803 18:49:00.831840 22923631028032 utils.py:23] Started Jackhmmer (uniref90.fasta) query
I0803 18:55:09.029107 22923631028032 utils.py:27] Finished Jackhmmer (uniref90.fasta) query in 368.197 seconds
Traceback (most recent call last):
  File "/applic/AlphaFold/current/run_alphafold.py", line 713, in <module>
    app.run(main, flags_parser=fasta_parser)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/applic/AlphaFold/current/run_alphafold.py", line 696, in main
    predict_structure(fasta_path=fasta_path,
  File "/applic/AlphaFold/current/run_alphafold.py", line 537, in predict_structure
    feature_dict = _preprocess(fasta_path, output_dir, data_pipeline, overwrite)
  File "/applic/AlphaFold/current/run_alphafold.py", line 417, in _preprocess
    feature_dict = data_pipeline.process(
  File "/applic/AlphaFold/2.2.6/alphafold/data/pipeline.py", line 171, in process
    jackhmmer_uniref90_result = run_msa_tool(
  File "/applic/AlphaFold/2.2.6/alphafold/data/pipeline.py", line 94, in run_msa_tool
    result = msa_runner.query(input_fasta_path, max_sto_sequences)[0]
  File "/applic/AlphaFold/2.2.6/alphafold/data/tools/jackhmmer.py", line 173, in query
    single_chunk_result = self._query_chunk(
  File "/applic/AlphaFold/2.2.6/alphafold/data/tools/jackhmmer.py", line 145, in _query_chunk
    'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 129: invalid start byte

**Comment by jnooree** [comment]
Please upload the fasta file caused this error.

**Comment by jesuissumin** [comment]
/home/sumin/GPCR_bench/GPCR2021/input_seq/T01_rec.fa

```fasta
>APJ
GALIPAIYMLVFLLGTTGNGLVLWTVFRSSREKRRSADIFIASLAVADLTFVVTLPLWATYTYRDYDWPFGTFFCKLSSYLIFVNMYASAFCLTGLSFDRYLAIVRPVANARLRLRVSGAVATAVLWVLAALLAMPVMVLRTTGDLCNTNKVQCYMDYSMVATVSSEWAWEVGLGVSSTTVGFVVPFTICLTCYFFIAQTIAMKKYTCTVCGYIYNPEDGDPDNGVNPGTDFKDIPDDWVCPLCGVGKDQFEEVEERRRLLSICVVLVVTFALCWMPYHLVKTLYMLGSLLHWPCDFDLFLMNIFPYCTCISYVNSCLNPFLYAFFDPRFRQACTSMLLMGQSRLEVLFQG
```

**Comment by jnooree** [comment]
This was triggered by a corrupted uniref90 database and was resolved by syncing the database again. Anyway, I'll submit a patch preventing similar issues shortly.
