### ISSUE TITLE
[BUG] Error after AlphaFold v2.3 (FAILED_PRECONDITION: Couldn't get ptxas version string: INTERNAL: Couldn't invoke ptxas --version)

### ISSUE THREAD

**Issue by yeopyeob** [seoklab/alphafold#6]
### Describe the bug

```
Traceback (most recent call last):
  File "/applic/AlphaFold/current/run_alphafold.py", line 751, in <module>
    app.run(main, flags_parser=fasta_parser)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/applic/AlphaFold/current/run_alphafold.py", line 732, in main
    predict_structure(
  File "/applic/AlphaFold/current/run_alphafold.py", line 571, in predict_structure
    results, ranking_confidences, unrelaxed_prots = _predict(
  File "/applic/AlphaFold/current/run_alphafold.py", line 451, in _predict
    dev_results = Parallel(n_jobs=n_jobs, backend="multiprocessing")(
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/parallel.py", line 1085, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/parallel.py", line 901, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/parallel.py", line 819, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 597, in __init__
    self.results = batch()
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/applic/AlphaFold/current/run_alphafold.py", line 395, in predict_structure_perdev
    return [
  File "/applic/AlphaFold/current/run_alphafold.py", line 396, in <listcomp>
    predict_structure_permodel(
  File "/applic/AlphaFold/current/run_alphafold.py", line 333, in predict_structure_permodel
    prediction_result = model_runner.predict(processed_feature_dict,
  File "/applic/AlphaFold/2.3/alphafold/model/model.py", line 184, in predict
    jax.random.PRNGKey(random_seed),
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/random.py", line 132, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 267, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 580, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 592, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 597, in random_seed_impl_base
    return seed(seeds)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/prng.py", line 832, in threefry_seed
    lax.shift_right_logical(seed, lax_internal._const(seed, 32)))
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 515, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 113, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/util.py", line 253, in wrapper
    return cached(config._trace_context(), *args, **kwargs)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/util.py", line 246, in cached
    return f(*args, **kwargs)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 197, in xla_primitive_callable
    compiled = _xla_callable_uncached(lu.wrap_init(prim_fun), device, None,
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 359, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 996, in compile
    self._executable = XlaCompiledComputation.from_xla_computation(
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 1194, in from_xla_computation
    compiled = compile_or_get_cached(backend, xla_computation, options,
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 1077, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/alphafold2/lib/python3.8/site-packages/jax/_src/dispatch.py", line 1012, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: Couldn't get ptxas version string: INTERNAL: Couldn't invoke ptxas --version
```

### Bug on which cluster?

Cluster 3

### Bug on which software versions?

AlphaFold2 v2.3

#### This repository

```
alphafold --max_template_date=2022-12-27 tot.fa >> tot.log
```

#### Related software

AlphaFold2 v2.3

### Additional context

My input file is like

```
> chain C
MASLTVKAYLLGKEDAAREIRRFSFCCSPEPEAEAEAAAGPGPCERLLSRVAALFPALRPGGFQAHYRDEDGDLVAFSSDEELTMAMSYVKDDIFRIYIKEKKECRRDHRPPCAQEAPRNMVHPNVICDGCNGPVVGTRYKCSVCPDYDLCSVCEGKGLHRGH
> n_term
RCDED
```

**Comment by jnooree** [comment]
Fixed by updating permission. Sorry!
